\set ON_ERROR_STOP on
BEGIN; SELECT pg_advisory_xact_lock(81723301);
CREATE TABLE IF NOT EXISTS suppliers(supplier_id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,supplier_code text UNIQUE NOT NULL,supplier_name text NOT NULL,contact_person text,email text UNIQUE,phone text,address text,city text,state text,country text NOT NULL DEFAULT 'India',payment_terms text NOT NULL,rating numeric(2,1) CHECK(rating BETWEEN 1 AND 5),status text NOT NULL CHECK(status IN('Active','Inactive','Suspended')));
CREATE TABLE IF NOT EXISTS products(product_id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,product_code text UNIQUE NOT NULL,product_name text NOT NULL,category text NOT NULL,unit text NOT NULL,cost_price numeric(14,2) CHECK(cost_price>0),selling_price numeric(14,2) CHECK(selling_price>=cost_price),reorder_level integer CHECK(reorder_level>=0),status text NOT NULL CHECK(status IN('Active','Discontinued')));
CREATE TABLE IF NOT EXISTS warehouses(warehouse_id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,warehouse_code text UNIQUE NOT NULL,warehouse_name text NOT NULL,location text,city text NOT NULL,capacity integer CHECK(capacity>0),manager_name text);
CREATE TABLE IF NOT EXISTS inventory(inventory_id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,product_id bigint NOT NULL REFERENCES products,warehouse_id bigint NOT NULL REFERENCES warehouses,quantity_on_hand integer CHECK(quantity_on_hand>=0),reserved_quantity integer CHECK(reserved_quantity>=0),available_quantity integer GENERATED ALWAYS AS(quantity_on_hand-reserved_quantity) STORED,reorder_level integer CHECK(reorder_level>=0),last_updated timestamptz NOT NULL DEFAULT now(),UNIQUE(product_id,warehouse_id),CHECK(reserved_quantity<=quantity_on_hand));
CREATE TABLE IF NOT EXISTS purchase_orders(purchase_order_id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,po_number text UNIQUE NOT NULL,supplier_id bigint NOT NULL REFERENCES suppliers,warehouse_id bigint NOT NULL REFERENCES warehouses,order_date date NOT NULL,expected_delivery_date date,actual_delivery_date date,subtotal numeric(14,2) NOT NULL,tax numeric(14,2) NOT NULL,total_amount numeric(14,2) NOT NULL,status text NOT NULL CHECK(status IN('Draft','Ordered','Partially Received','Received','Cancelled')));
CREATE TABLE IF NOT EXISTS purchase_order_items(po_item_id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,purchase_order_id bigint NOT NULL REFERENCES purchase_orders ON DELETE CASCADE,product_id bigint NOT NULL REFERENCES products,quantity integer CHECK(quantity>0),unit_cost numeric(14,2) CHECK(unit_cost>0),total_cost numeric(14,2) CHECK(total_cost>0),UNIQUE(purchase_order_id,product_id));
CREATE TABLE IF NOT EXISTS customers(customer_id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,customer_code text UNIQUE NOT NULL,customer_name text NOT NULL,industry text NOT NULL,city text NOT NULL,state text NOT NULL,country text NOT NULL DEFAULT 'India',credit_limit numeric(14,2) CHECK(credit_limit>=0),status text NOT NULL CHECK(status IN('Active','Inactive','Credit Hold')));
CREATE TABLE IF NOT EXISTS sales_orders(sales_order_id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,order_number text UNIQUE NOT NULL,customer_id bigint REFERENCES customers,customer_name text NOT NULL,order_date date NOT NULL,warehouse_id bigint NOT NULL REFERENCES warehouses,subtotal numeric(14,2) NOT NULL,tax numeric(14,2) NOT NULL,discount numeric(14,2) NOT NULL DEFAULT 0,total_amount numeric(14,2) NOT NULL,payment_status text NOT NULL CHECK(payment_status IN('Pending','Partially Paid','Paid','Overdue')),order_status text NOT NULL CHECK(order_status IN('Confirmed','Processing','Shipped','Delivered','Cancelled')));
CREATE TABLE IF NOT EXISTS sales_order_items(sales_item_id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,sales_order_id bigint NOT NULL REFERENCES sales_orders ON DELETE CASCADE,product_id bigint NOT NULL REFERENCES products,quantity integer CHECK(quantity>0),unit_price numeric(14,2) CHECK(unit_price>0),discount numeric(14,2) NOT NULL DEFAULT 0,total numeric(14,2) CHECK(total>=0),UNIQUE(sales_order_id,product_id));
CREATE TABLE IF NOT EXISTS invoices(invoice_id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,invoice_number text UNIQUE NOT NULL,sales_order_id bigint UNIQUE NOT NULL REFERENCES sales_orders,invoice_date date NOT NULL,due_date date NOT NULL,subtotal numeric(14,2) NOT NULL,tax numeric(14,2) NOT NULL,total_amount numeric(14,2) NOT NULL,paid_amount numeric(14,2) NOT NULL DEFAULT 0,outstanding_amount numeric(14,2) NOT NULL,payment_status text NOT NULL CHECK(payment_status IN('Unpaid','Partially Paid','Paid','Overdue')),CHECK(due_date>=invoice_date),CHECK(outstanding_amount>=0));
CREATE TABLE IF NOT EXISTS payments(payment_id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,invoice_id bigint NOT NULL REFERENCES invoices,payment_date date NOT NULL,amount numeric(14,2) CHECK(amount>0),payment_method text NOT NULL CHECK(payment_method IN('UPI','Bank Transfer','Card','Cheque')),transaction_reference text UNIQUE NOT NULL,status text NOT NULL CHECK(status IN('Captured','Failed','Pending')));
CREATE TABLE IF NOT EXISTS expenses(expense_id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,expense_category text NOT NULL,department text NOT NULL,description text,amount numeric(14,2) CHECK(amount>0),expense_date date NOT NULL,approved_by text,status text NOT NULL CHECK(status IN('Submitted','Approved','Paid','Rejected')));
CREATE TABLE IF NOT EXISTS shipments(shipment_id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,shipment_number text UNIQUE NOT NULL,sales_order_id bigint UNIQUE NOT NULL REFERENCES sales_orders,warehouse_id bigint NOT NULL REFERENCES warehouses,shipment_date date,expected_delivery_date date,actual_delivery_date date,carrier text,tracking_number text UNIQUE,shipping_status text NOT NULL CHECK(shipping_status IN('Preparing','In Transit','Delivered','Delayed','Returned')));
CREATE INDEX IF NOT EXISTS idx_inventory_stock ON inventory(warehouse_id,available_quantity); CREATE INDEX IF NOT EXISTS idx_po_date_status ON purchase_orders(order_date,status); CREATE INDEX IF NOT EXISTS idx_so_date_status ON sales_orders(order_date,order_status); CREATE INDEX IF NOT EXISTS idx_invoice_due_status ON invoices(due_date,payment_status); CREATE INDEX IF NOT EXISTS idx_expense_date_category ON expenses(expense_date,expense_category); CREATE INDEX IF NOT EXISTS idx_shipment_status ON shipments(shipping_status);
COMMENT ON COLUMN inventory.available_quantity IS 'On-hand quantity less reservations; compare with reorder_level for low-stock analysis.'; COMMENT ON COLUMN invoices.outstanding_amount IS 'Invoice balance still due in INR.'; COMMENT ON COLUMN payments.status IS 'Payment processing state; Captured payments contribute to collections.';
COMMIT;
