\set ON_ERROR_STOP on
BEGIN; SELECT pg_advisory_xact_lock(81723201);
CREATE TABLE IF NOT EXISTS sales_representatives(sales_rep_id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,employee_code text UNIQUE NOT NULL,name text NOT NULL,email text UNIQUE NOT NULL,territory text NOT NULL,region text NOT NULL,target_amount numeric(14,2) CHECK(target_amount>0),status text NOT NULL CHECK(status IN('Active','Inactive')));
CREATE TABLE IF NOT EXISTS customers(customer_id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,customer_code text UNIQUE NOT NULL,first_name text,last_name text,company_name text NOT NULL,email text UNIQUE,phone text,industry text NOT NULL,customer_type text NOT NULL CHECK(customer_type IN('SMB','Mid-Market','Enterprise')),city text NOT NULL,state text NOT NULL,country text NOT NULL DEFAULT 'India',acquisition_channel text NOT NULL,customer_status text NOT NULL CHECK(customer_status IN('Active','Inactive','Prospect')),created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS leads(lead_id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,lead_code text UNIQUE NOT NULL,first_name text,last_name text,company_name text NOT NULL,email text UNIQUE,phone text,source text NOT NULL,industry text NOT NULL,assigned_to bigint NOT NULL REFERENCES sales_representatives,lead_score integer CHECK(lead_score BETWEEN 0 AND 100),lead_status text NOT NULL CHECK(lead_status IN('New','Contacted','Qualified','Converted','Disqualified')),created_at timestamptz NOT NULL,converted_at timestamptz CHECK(converted_at IS NULL OR converted_at>=created_at));
CREATE TABLE IF NOT EXISTS opportunities(opportunity_id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,opportunity_code text UNIQUE NOT NULL,customer_id bigint NOT NULL REFERENCES customers,sales_rep_id bigint NOT NULL REFERENCES sales_representatives,opportunity_name text NOT NULL,opportunity_stage text NOT NULL CHECK(opportunity_stage IN('Discovery','Qualification','Proposal','Negotiation','Closed Won','Closed Lost')),probability integer CHECK(probability BETWEEN 0 AND 100),estimated_value numeric(14,2) CHECK(estimated_value>0),expected_close_date date,actual_close_date date,status text NOT NULL CHECK(status IN('Open','Won','Lost')),created_at timestamptz NOT NULL);
CREATE TABLE IF NOT EXISTS activities(activity_id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,customer_id bigint REFERENCES customers,lead_id bigint REFERENCES leads,opportunity_id bigint REFERENCES opportunities,sales_rep_id bigint NOT NULL REFERENCES sales_representatives,activity_type text NOT NULL CHECK(activity_type IN('Call','Email','Meeting','Demo','Follow-up')),subject text NOT NULL,activity_date timestamptz NOT NULL,duration_minutes integer CHECK(duration_minutes>=0),outcome text,notes text,CHECK(customer_id IS NOT NULL OR lead_id IS NOT NULL OR opportunity_id IS NOT NULL));
CREATE TABLE IF NOT EXISTS customer_contacts(contact_id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,customer_id bigint NOT NULL REFERENCES customers,contact_name text NOT NULL,designation text,email text,phone text,contact_role text,is_primary boolean NOT NULL DEFAULT false);
CREATE TABLE IF NOT EXISTS products(product_id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,product_code text UNIQUE NOT NULL,product_name text NOT NULL,category text NOT NULL,description text,unit_price numeric(14,2) CHECK(unit_price>0),status text NOT NULL CHECK(status IN('Active','Retired')));
CREATE TABLE IF NOT EXISTS quotes(quote_id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,quote_number text UNIQUE NOT NULL,customer_id bigint NOT NULL REFERENCES customers,opportunity_id bigint NOT NULL REFERENCES opportunities,sales_rep_id bigint NOT NULL REFERENCES sales_representatives,quote_date date NOT NULL,valid_until date NOT NULL,subtotal numeric(14,2) NOT NULL,discount numeric(14,2) NOT NULL DEFAULT 0,tax numeric(14,2) NOT NULL,total_amount numeric(14,2) NOT NULL,status text NOT NULL CHECK(status IN('Draft','Sent','Accepted','Rejected','Expired')),CHECK(valid_until>=quote_date));
CREATE TABLE IF NOT EXISTS quote_items(quote_item_id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,quote_id bigint NOT NULL REFERENCES quotes ON DELETE CASCADE,product_id bigint NOT NULL REFERENCES products,quantity integer CHECK(quantity>0),unit_price numeric(14,2) CHECK(unit_price>0),discount numeric(14,2) NOT NULL DEFAULT 0,total numeric(14,2) CHECK(total>=0),UNIQUE(quote_id,product_id));
CREATE TABLE IF NOT EXISTS customer_tickets(ticket_id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,ticket_number text UNIQUE NOT NULL,customer_id bigint NOT NULL REFERENCES customers,assigned_to bigint NOT NULL REFERENCES sales_representatives,priority text NOT NULL CHECK(priority IN('Low','Medium','High','Critical')),category text NOT NULL,subject text NOT NULL,description text,status text NOT NULL CHECK(status IN('Open','In Progress','Resolved','Closed')),created_at timestamptz NOT NULL,resolved_at timestamptz CHECK(resolved_at IS NULL OR resolved_at>=created_at));
CREATE INDEX IF NOT EXISTS idx_customer_industry_status ON customers(industry,customer_status); CREATE INDEX IF NOT EXISTS idx_lead_status_source ON leads(lead_status,source); CREATE INDEX IF NOT EXISTS idx_opportunity_stage_close ON opportunities(opportunity_stage,expected_close_date); CREATE INDEX IF NOT EXISTS idx_activity_date ON activities(activity_date); CREATE INDEX IF NOT EXISTS idx_ticket_status_created ON customer_tickets(status,created_at);
COMMENT ON COLUMN leads.lead_status IS 'Lead funnel state; Converted indicates a successful conversion.'; COMMENT ON COLUMN opportunities.opportunity_stage IS 'Current sales-funnel stage.'; COMMENT ON COLUMN opportunities.estimated_value IS 'Potential contract value in INR.';
COMMIT;
