"""Data models and schemas."""

from models.schemas import (
    AnalyticsOutput,
    BaselineComparison,
    DatabaseSchema,
    EvidenceQuery,
    EvidenceResult,
    FilterCondition,
    IntentOutput,
    PipelineResult,
    Relationship,
    RootCauseHypothesis,
    RootCauseOutput,
    SQLOutput,
    TableMetadata,
)
from models.mock_schema import (
    ECOMMERCE_SCHEMA,
    HRMS_SCHEMA,
    get_mock_schema_by_domain,
)
from models.mock_data import (
    MOCK_MONTHLY_REVENUE_TREND,
    MOCK_REVENUE_BY_CATEGORY,
    MOCK_SINGLE_KPI_THIS_MONTH,
    MOCK_EMPLOYEE_DISTRIBUTION,
    MOCK_DECLINING_SALES_SCENARIO,
    MOCK_CATEGORY_SALES_DURING_DECLINE,
    MOCK_RCA_BASELINE,
    MOCK_RCA_EVIDENCE_CATEGORY,
    MOCK_RCA_EVIDENCE_REGION,
    MOCK_RCA_EVIDENCE_VOLUME_AOV,
    MOCK_RCA_EVIDENCE_CANCELLATION,
)

__all__ = [
    "AnalyticsOutput",
    "BaselineComparison",
    "DatabaseSchema",
    "EvidenceQuery",
    "EvidenceResult",
    "FilterCondition",
    "IntentOutput",
    "PipelineResult",
    "Relationship",
    "RootCauseHypothesis",
    "RootCauseOutput",
    "SQLOutput",
    "TableMetadata",
    "ECOMMERCE_SCHEMA",
    "HRMS_SCHEMA",
    "get_mock_schema_by_domain",
    "MOCK_MONTHLY_REVENUE_TREND",
    "MOCK_REVENUE_BY_CATEGORY",
    "MOCK_SINGLE_KPI_THIS_MONTH",
    "MOCK_EMPLOYEE_DISTRIBUTION",
    "MOCK_DECLINING_SALES_SCENARIO",
    "MOCK_CATEGORY_SALES_DURING_DECLINE",
    "MOCK_RCA_BASELINE",
    "MOCK_RCA_EVIDENCE_CATEGORY",
    "MOCK_RCA_EVIDENCE_REGION",
    "MOCK_RCA_EVIDENCE_VOLUME_AOV",
    "MOCK_RCA_EVIDENCE_CANCELLATION",
]
